### ISSUE TITLE
Make it work with imgbot

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#205] opened 2021-03-31 20:01 UTC
ImgBot is a bot on GitHub that automatically optimizes images and can optimize svgs. Make it so it is optimized so that imgbot is happy and doesn't keep sending PRs on the repo.
Thanks!
[ImgBot](https://imgbot.net/)

**Comment by lowlighter** [comment] 2021-04-01 06:55
This won't be possible until #172 is solved, since imgbot uses SVGO under the hood to optimize images.
You can actually notice [that spaces are removed from tweets and activity plugins](https://github.com/Milo123459/Milo123459/blob/imgbot/github-metrics.svg)

**Comment by lowlighter** [comment] 2021-04-01 07:12
(closing as it's kind of duplicate of #172, since using SVGO is the same as using imgbot for SVG images)

**Closed by lowlighter** 2021-04-01 07:12 UTC
