### ISSUE TITLE
Metrics thinks rs file extension is renderscript

### ISSUE THREAD

**Issue by Milo123459** [lowlighter/metrics#551] opened 2021-10-03 21:19 UTC
I have never used renderscript, but the module that shows the recently committed language usage is displaying as i have, when in reality it's rust

**Comment by Nixinova** [comment] 2021-10-03 22:23
This would be an issue with https://github.com/Nixinova/Lingusit. Do you know what repository/-ies Metrics would be checking? I cloned a couple you've contrib'd to (vext,starship,salt,spotify-tui) and none of them outputted renderscript.

**Comment by Milo123459** [comment] 2021-10-04 08:00
Closed source :(

**Comment by Milo123459** [comment] 2021-10-04 15:46
<img width="365" alt="qW65WOID" src="https://user-images.githubusercontent.com/50248166/135882399-51c8e656-7333-42d2-9d7e-e8ac5201dc0e.png">

**Comment by Nixinova** [comment] 2021-10-08 04:32
>  (IIRC linguist use the file extension and maybe look at content but not sure about the latter)

linguist-js does everything github-linguist does except for classification based on samples

**Comment by spenserblack** [comment] 2021-10-20 02:08
Looks like I'm experiencing this bug now, too: https://github.com/spenserblack/spenserblack/commit/aa76d675ec5ceaf5d49f2d71f86e92daa38b53cb

I suppose one of my commits in the past 24 hours is the cause. [This should be the only Rust commit I made around that time](https://github.com/o2sh/onefetch/commit/f11777cbdf417665f28b91167b0f248876a57f0f).

**Comment by Nixinova** [comment] 2021-10-21 01:10
Running linguist-js on that repo doesn't show any RenderScript - is there any other Rust you may have contributed?
![image](https://user-images.githubusercontent.com/42429413/138193352-ed09b692-8d3e-4ac0-852a-64fcc6cf5d94.png)

**Comment by spenserblack** [comment] 2021-10-21 01:51
As far as recent contributions, the only other Rust project should be [this one](https://github.com/spenserblack/change-git-user). But I'm not sure if that project is the cause, since my recent commits there were just changed the TOML file, not any Rust code itself.

**Comment by Nixinova** [comment] 2021-10-21 04:18
> How does it react to an empty .gitattributes file?

It should be no different from no file.

> Oh, I should mention that this is with lowlighter/metrics@v3.14, which has a slightly lower version of linguist-js than @master.

My screenshot was from linguist-js@2.1.1 so that's not the problem

**Comment by matievisthekat** [comment] 2021-11-12 10:47
I am also experiencing this issue.

The commits would probably be from matievisthekat/chum@891a8b434f36f5db782605edf275bc9d06a84e04 to matievisthekat/chum@e897954f4b1a215f3524f152217ead968f7ecef3.

GitHub classifies the repo as Rust but the metrics plugin includes RenderScript in my Recently Used Languages (image)

![Screenshot from 2021-11-12 12-41-46](https://user-images.githubusercontent.com/45036977/141454194-1eca3ed3-3895-43d8-ae22-a21932c27515.png)

I am on `lowlighter/metrics@master` and this is still an issue. (I ran the workflow now to confirm)

Is there any fix available?

**Comment by lowlighter** [comment] 2021-11-13 00:49
@matievisthekat 
Thanks a lot for providing resources that we can use to go forward with this issue 👍 
There's no fix yet, but with #661 you'll be able to use `plugin_languages_aliases: RenderScript:Rust` as a workaround while this is still under resolution

With what you provided, I was indeed able to reproduce the result with an extract of your repository [matievisthekat/chum](https://github.com/matievisthekat/chum) ([full extract.zip](https://github.com/lowlighter/metrics/files/7530995/extract.zip))

When running `linguist-js` directly on it, it does output the same output as Metrics is currently displaying: 
```js
//npx linguist-js --analyze /tmp/matievisthekat@chum/src/ --json
{
  files: {
    count: 7,
    bytes: 4818,
    results: {
      '/tmp/matievisthekat@chum/src/cli.rs': 'RenderScript',
      '/tmp/matievisthekat@chum/src/lib/cli.rs': 'Rust',
      '/tmp/matievisthekat@chum/src/lib/commands.rs': 'Rust',
      '/tmp/matievisthekat@chum/src/lib/command_manager.rs': 'RenderScript',
      '/tmp/matievisthekat@chum/src/lib/display.rs': 'Rust',
      '/tmp/matievisthekat@chum/src/lib/mod.rs': 'Rust',
      '/tmp/matievisthekat@chum/src/main.rs': 'RenderScript'
    }
  },
  languages: {
    count: 2,
    bytes: 4818,
    results: {
      RenderScript: { type: 'programming', bytes: 2452, color: undefined },
      Rust: { type: 'programming', bytes: 2366, color: '#dea584' }
    }
  },
  unknown: { count: 0, bytes: 0, extensions: {}, filenames: {} }
}
```

I looked a bit into the content of two file with same names, with one being flagged as Rust and the other one as RenderScript.
What's surprising is that the sample for the RenderScript one is actually larger thatn the Rust one:
(note that code is not valid code, since only lines from GitHub event patches are processed)

<details>

<summary>src/cli.rs extract, "RenderScript"</summary>

```rust
type Result = std::result::Result<i32, (i32, String)>;
  pub fn run(&self) {
    let exit: Result;
    match exit {
      Ok(code) => std::process::exit(code),
      Err((code, message)) => {
        eprintln!("{}", message);
        std::process::exit(code)
      }
    }
          return Err((127, "No command specified".to_string()));
          return Err((127, format!("Unknown command: {}", self.command)));andlers: HashMap::new(),
      flag_handlers: HashMap::new(),
    cli.parse();

    cli
  }

  pub fn run(&self) -> &Self {
    let command_handler = self.command_handlers.get(&self.command);
    let context = Context {
      cli: self.clone(),
      args: self.args.clone(),
    };
    let mut exit: Result = Err((
      1,
      "No result returned from command handler. Please report this".to_string(),
    ));

    if self.command.is_empty() && self.flags.len() > 0 {
      let flag_handler = self.flag_handlers.get(&self.flags[0]);
      exit = self.match_flag_handler(flag_handler, &context);
    } else {
      exit = self.match_command_handler(command_handler, &context);
    }

    self
  }

  pub fn register_command(&mut self, command: &str, handler: Handler) {
    self.command_handlers.insert(command.to_string(), handler);
  }

  pub fn register_flag(&mut self, flag: &str, handler: Handler) {
    self.flag_handlers.insert(flag.to_string(), handler);
  }

  fn match_command_handler(&self, command_handler: Option<&Handler>, context: &Context) -> Result {
    match command_handler {
      Some(handler) => return handler(context),
      None => {
        if self.command.is_empty() {
          return Err((1, "No command specified".to_string()));
        } else {
          return Err((1, format!("Unknown command: {}", self.command)));
        }
      }
    };
  }

  fn match_flag_handler(&self, flag_handler: Option<&Handler>, context: &Context) -> Result {
    match flag_handler {
      Some(handler) => return handler(context),
      None => return Err((1, format!("Unknown flag: {}", self.flags[0]))),
    }
  fn parse(&mut self) -> &Self {
```

</details>

<details>

<summary>src/lib/cli.rs extract "Rust"</summary>

```rust
use crate::lib::{command_manager, display::Display};
  commands: HashMap<String, command_manager::Command>,
  flag_handlers: HashMap<String, command_manager::Handler>,
    let exit: command_manager::Result;
  pub fn register_command(&mut self, command: command_manager::Command) {
  pub fn register_flag(&mut self, flag: &str, handler: command_manager::Handler) {
    command: Option<&command_manager::Command>,
  ) -> command_manager::Result {
    flag_handler: Option<&command_manager::Handler>,
  ) -> command_manager::Result {
```

</details>

However, cloning the original repository and running `linguist-js` will yield the correct results:
```js
//npx linguist-js --analyze /tmp/chum --json
{
  files: {
    count: 7,
    bytes: 6886,
    results: {
      '/tmp/chum/Cargo.toml': 'TOML',
      '/tmp/chum/README.md': 'Markdown',
      '/tmp/chum/src/lib/cli.rs': 'Rust',
      '/tmp/chum/src/lib/command_manager.rs': 'Rust',
      '/tmp/chum/src/lib/display.rs': 'Rust',
      '/tmp/chum/src/lib/mod.rs': 'Rust',
      '/tmp/chum/src/main.rs': 'Rust'
    }
  },
  languages: {
    count: 3,
    bytes: 6886,
    results: {
      TOML: { type: 'data', bytes: 212, color: '#9c4221' },
      Markdown: { type: 'prose', bytes: 505, color: '#083fa1' },
      Rust: { type: 'programming', bytes: 6169, color: '#dea584' }
    }
  },
  unknown: { count: 0, bytes: 0, extensions: {}, filenames: {} }
}
```

Maybe @Nixinova will be able to provide more informations

**Comment by Nixinova** [comment] 2021-11-13 03:16
These are the heuristics for the `.rs` classification:
https://github.com/github/linguist/blob/dc577fe72a28ab069f02cc002b4f2e3851a72f93/lib/linguist/heuristics.yml#L504-L510
![image](https://user-images.githubusercontent.com/42429413/141603757-b7afd752-f40d-42e6-a7ac-eeda63403336.png)

The heuristics aren't matching because the Rust heuristic doesn't count whitespace before the token as valid: `^(pub|fn)` doesn't match the provided file content of `   pub fn`.

Since the heuristics don't match the classification defaults to the first language in the alphabetically-sorted list, which in this case is RenderScript.

So RenderScript shows up because it's the default/fallback.

**Comment by lowlighter** [comment] 2021-11-13 04:39
Since most heuristics have an optional number of leading of whitespaces, I think it would be actually safe to trim code from events.
But maybe it'd introduce other issues ?

**Comment by spenserblack** [comment] 2021-11-13 07:00
I see that Rust is positionally before RenderScript in the `rules` array for `.rs`. If the heuristics cannot classify, would it make sense to take the first positional language over the first alphabetical language in linguist-js? I'm pretty sure that Rust is much more popular than RenderScript, so an unclassified `.rs` file is likely Rust.

**Comment by Nixinova** [comment] 2021-11-13 19:52
> If the heuristics cannot classify, would it make sense to take the first positional language over the first alphabetical language in linguist-js?

Looking through the [heuristics list](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) it seems the more general language is *last* positionally.
![image](https://user-images.githubusercontent.com/42429413/141657252-2de9febb-56f6-4095-9f07-402499e73192.png)

**Comment by lowlighter** [comment] 2022-02-04 00:28
Closing as it's an external issue and not in scope 👍

**Closed by lowlighter** 2022-02-04 00:28 UTC
Labels: 🐛 bug, ↩️ external issue, 🈷️ plugin languages

**Comment by Nixinova** [comment] 2022-02-04 00:38
>Closing as it's an external issue and not in scope

Is [this](https://github.com/lowlighter/metrics/issues/551#issuecomment-948570921) issue no longer occurring?

**Comment by lowlighter** [comment] 2022-02-04 04:36
I'm not sure since I don't code in rust 😕 

But in any case I don't think this is something that can be solved within this repository scope.
Language guessing isn't an exact science anyway so false positives are bound to happen I guess ¯\\_(ツ)_/¯

___

I'm closing this because I'm currently cleaning the backlog

Plan is to make the issues tab of this repo an untimed roadmap (kind like a todo-list) containing fixes and features that *will be eventually worked on* in the future. The discussions tab will be used for everything else, including bug reports and feature requests that may be promoted to the issue tab if they're revelant and/or possible.
 
I hope it'll make it easier for everyone to see upcoming changes and also make contributing easier by ensuring that everything in the issue tab is actually doable and that it is within scope
