### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by awesomelewis2007** [lowlighter/metrics#1392] opened 2023-03-04 12:05 UTC
### Discussed in https://github.com/lowlighter/metrics/discussions/1390

<div type='discussions-op-text'>

<sup>Originally posted by **PhilipDeegan** March  3, 2023</sup>
https://metrics.lecoq.io/ 
![image](https://user-images.githubusercontent.com/30491/222850653-c5fe07bc-879a-4a92-83f9-abed02a3fe77.png)
</div>

**Comment by Paraguanads** [comment] 2023-03-05 18:28
Facing the same issue here.

**Comment by IMpcuong** [comment] 2023-03-06 09:46
> Facing the same issue here.

`Invalid SSL Certificate`: I think the root cause is kind of clear; the SSL certificate for `metrics.lecoq.io` has expired, and all we can do is wait until the website's maintainer renews the certification.

**Comment by WillDev12** [comment] 2023-03-08 13:02
Same problem here, don't know much about SSL related stuff but I can tell that the maintainer of the domain needs to fix it.

**Comment by lowlighter** [comment] 2023-03-13 01:35
Hi 👋 !

Sorry I got really busy these days, but this should be fixed now 👍 
Sometimes the post trigger of certbot renew get killed so the cert is renewed but nginx isn't restarted so it still keep the old certificate 😅 

Thanks for reporting this !

**Closed by lowlighter** 2023-03-13 01:35 UTC
